### PR TITLE
Change the variable type and fixed typo and words in BROWSER.js file

### PR DESCRIPTION
**Pull request by heeyoun-song**
* If you do not need to reassign, change the variable type from 'let' to 'const'.
* Fixed typo and words in BROWSER.js file
  - 실글톤 -> 싱글톤

### CODE REVIEW

**Comment by heeyoun-song** [comment]
Fixed typo and words in BROWSER.js file

 - 실글톤 -> 싱글톤

**Comment by heeyoun-song** [comment]
Do you use Intellij IDEA? If you use it, please share the formatting file.

**Comment by heeyoun-song** [comment]
Or use Airbnb's jslint. There is also an npm module which is easy to apply.

**Comment by Hanul** [comment]
안녕하세요, 풀리퀘스트 작성해주셔서 대단히 감사합니다. 혹시 `let`을 `const`로 바꾸는데 있어서 어떤 툴을 사용하셨는지 여쭈어봅니다 :)

**Comment by heeyoun-song** [comment]
Manual change and corrected the compile error. :)

**Comment by heeyoun-song** [comment]
It was hard to fix. Please accept the pull request. :):)

**Comment by heeyoun-song** [comment]
@Hanul 
Is there anything else you need to modify?
I hope that the changes will be merged into the master branch.

**Comment by heeyoun-song** [comment]
...

**Comment by heeyoun-song** [comment]
**Close the pull request because you no longer think the store is managed.**

**Pull request closed without merging**
